### ISSUE TITLE
Encodage des caractères

### ISSUE THREAD

**Issue by rcharre** [Tanaguru/webextension#13]
Actuellement la webextension injecte le texte de l'affichage via element.innerHtml ce qui fait que les développeurs doivent gérer l'encodage des caractères dans la création des tests.

Il faudrait modifier l'injection pour utiliser textContent  à la place et ainsi ne plus à avoir à gérer l'encodage dans les fichiers de tests.

**Comment by severineFF-tanaguru** [comment]
Corrigé sur ce commit : [character encoding](https://github.com/Tanaguru/webextension/commit/deeacc76510be5a2ca103588b2f5d07cdebed58c)

Je te laisse fermer l'issue si c'est ok pour toi.

**Comment by rcharre** [comment]
Super ! Merci beaucoup :)
