### ISSUE TITLE
Webextention latency

### ISSUE THREAD

**Issue by nmadeuf** [Tanaguru/webextension#3]
When testing some pages/websites with the webextension, the extention loads for ever and never return results. 
Example of pages I tried to test: 
https://www.quality.cms-one.richemont.com/us/en/home.html
https://www.iwc.com/us/en/home.html
Note: on other, more simple pages, it works fine! :)

**Comment by rgervois-oceane** [comment]
Corrigé dans la version de ce jour (problème causé par des tests mal implémentés).
